### ISSUE TITLE
Encryption Failure for Non-Latin Characters

### ISSUE THREAD

**Issue by vtshly** [duydl/logseq-privacy-mode#3]
### Environment: 
- Plugin version v.1.2.8

### Description:
The **encryption fails** to properly encrypt text containing **non-Latin characters**. Attempting to encrypt a non-Latin line has no effect.

### Steps to Reproduce:

1. Add private block by snippet command -  {{renderer privacymode, encrypt}} #_encrypted 
2. Below the private block, enter child text-blocks containing non-Latin characters (e.g., Русский, 中文, العربية).
3. Click the padlock icon to initiate the encryption process.

### Expected Result:
The text-blocks should be encrypted correctly, regardless of the character set.

### Actual Result:
Non-Lating symbols are ignored for encryption. Error in console: 

> 'Uncaught (in promise) DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range' 

### Attachements

https://github.com/duydl/logseq-privacy-mode/assets/107392493/4304fc42-0d40-48ef-a8c1-8c2e466466a5

**Comment by duydl** [comment]
Without encryption password in this field, the plugin used `btoa` which doesn't support Unicode characters. 
![image](https://github.com/duydl/logseq-privacy-mode/assets/56506156/e1d33417-2752-42e2-9b09-05fda42a4714)
