### ISSUE TITLE
Base64 vs actual encryption

### ISSUE THREAD

**Issue by ybymentario** [duydl/logseq-privacy-mode#5]
Hey, thanks for the plug-in - it's really useful.

Of course, the 'encrypt' feature just uses Base64, which is easy to decode. The use case seems to be more for obscuring content at a glance (eg when screen sharing) rather than protecting your data. I'm not sure if it's possible on Logseq, but it would be great to see actual encryption in a future update.

**Comment by duydl** [comment]
Hi. If you set the password, it will use different algo to encrypt. The Base64 as default is admittedly not good design but it is a little complicated to change after I published the plugin.
