### ISSUE TITLE
DB version?

### ISSUE THREAD

**Issue by kerim** [duydl/logseq-privacy-mode#6]
I know plugin support isn't there yet for the DB version, but I really hope this plugin will continue to work there. Also curious how it will work to migrate encrypted notes to the DB version? Will it be necessary to un-encrypt before import, or will it "just work" after importing? Thanks!

**Comment by duydl** [comment]
Hi. Glad you find this small one useful. I will update it when the DB is out and the new extension system is stable. 
Import the encrypted file directly to the DB would still work (there even external tool to decrypt the text) but please make backup.
